language: java
install:
  - true
jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.gradle

script:
  - ./gradlew clean build

after_success:
  - bash <(curl -s https://codecov.io/bash)
